version: '2'

services:
  elastic:
    image: ligero/elasticsearch:5.6
    volumes:
      - ligero-elastic-data:/usr/share/elasticsearch/data
      - ligero-elastic-config:/usr/share/elasticsearch/config
      - ligero-elastic-plugins:/usr/share/elasticsearch/plugins
    environment:
      - cluster.name=otrs-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  ligero-elastic-data: ~
  ligero-elastic-config: ~
  ligero-elastic-plugins: ~

