version: '3.7'


services:
  elasticsearch:
    image: ligero/elasticsearch:7.8.0
    hostname: "node_{{.Task.Slot}}"
    container_name: "node_{{.Task.Slot}}"
    environment:
      - cluster.name=es-cluster
      - discovery.seed_hosts=tasks.elasticsearch
      - cluster.initial_master_nodes=node_1
      - "ES_JAVA_OPTS=-Xms3g -Xmx3g"
      - path.repo=/backups
      - bootstrap.memory_lock=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.monitoring.enabled=false
    volumes:
      - data-node:/usr/share/elasticsearch/data
      - backups:/backups
    networks:
      - default
      - web
    deploy:
       mode: replicated
       replicas: 2
       labels:
         - traefik.enable=true
         - traefik.port=9200
         - traefik.frontend.rule=Host:${WEBSERVER_FQDN}
         - traefik.protocol=http
         - traefik.docker.network=web
         - traefik.frontend.auth.basic.users=es:$$apr1$$6fZUtdag$$1.flATL/7KdtPWBHoqEIM/
       placement:
         constraints:
         - node.labels.database == true
         
  elastichq:
    image: elastichq/elasticsearch-hq
    environment:
      HQ_DEFAULT_URL: http://elasticsearch:9200
    networks:
      - default
      - web
    deploy:
       mode: replicated
       replicas: 1
       labels:
         - traefik.enable=true
         - traefik.port=5000
         - traefik.frontend.rule=Host:${EDITOR_FQDN}
         - traefik.protocol=http
         - traefik.docker.network=web
         
volumes:
  data-node:
    driver: local
    name: 'elasticsearch-cluster-v7_node-{{.Task.Slot}}'
  backups:
    driver: local
    
    
networks:
  web:
    external:
      name: web
